# frozen_string_literal: true

source "https://rubygems.org"

gemspec

# Minitest is bundled with the Ruby stdlib but we list it explicitly
# so `bundle install` is a no-op even on minimal Ruby distributions.
group :test do
  gem "minitest", "~> 5.0"
  gem "rake", "~> 13.0"
end
